### ISSUE TITLE
XmlValidator error message not informative

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#192]
It would be very helpful to see what file actually failed the validation.
Current exception say nothing about this
```
com.qulice.spi.ValidationException: XML validation exception (see log above)
	at com.qulice.xml.XmlValidator.validate(XmlValidator.java:70)
	at com.qulice.xml.XmlValidatorTest.passesValidationOnCorrectFile(XmlValidatorTest.java:69)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
```

**Comment by krzyk** [comment]
@longtimeago Right now qulice should report what needs to change in xml to pass validation, if so, please close this issue.

**Comment by longtimeago** [comment]
@krzyk OK, thanks
