### ISSUE TITLE
Build sometimes fails with Connection reset from XmlValidator

### ISSUE THREAD

**Issue by krzyk** [teamed/qulice#280]
This is probably related to parent upgrade to 0.21:
```
[INFO] --- qulice-maven-plugin:0.8.2:check (jcabi-check) @ qulice ---
[INFO] LICENSE found: file:/home/sg0891848/dev/tpc2/qulice/qulice/LICENSE.txt
log4j:WARN No appenders could be found for logger (org.apache.commons.beanutils.converters.BooleanConverter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] No Checkstyle violations found in 3 files
[INFO] No files to check with PMD
[INFO] No PMD violations found in 0 files
[INFO] /src/site/site.xml: to be validated
[ERROR] JSR-303 validator failed to initialize: Unable to create a Configuration, because no Bean Validation provider could be found. Add a provider like Hibernate Validator (RI) to your classpath. (see http://www.jcabi.com/jcabi-aspects/jsr-303.html)
[INFO] jcabi-aspects 0.15/1409f87 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] qulice ............................................ FAILURE [  4.070 s]
[INFO] qulice-spi ........................................ SKIPPED
[INFO] qulice-checkstyle ................................. SKIPPED
[INFO] qulice-codenarc ................................... SKIPPED
[INFO] qulice-findbugs ................................... SKIPPED
[INFO] qulice-pmd ........................................ SKIPPED
[INFO] qulice-xml ........................................ SKIPPED
[INFO] qulice-maven-plugin ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.943 s
[INFO] Finished at: 2014-06-14T08:18:18+01:00
[INFO] Final Memory: 23M/347M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.8.2:check (jcabi-check) on project qulice: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.8.2:check failed: java.net.SocketException: Connection reset -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.8.2:check (jcabi-check) on project qulice: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.8.2:check failed: java.net.SocketException: Connection reset
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.8.2:check failed: java.net.SocketException: Connection reset
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.IllegalStateException: java.net.SocketException: Connection reset
	at com.qulice.xml.XmlValidator.validate(XmlValidator.java:91)
	at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
	at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 20 more
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:196)
	at java.net.SocketInputStream.read(SocketInputStream.java:122)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:235)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:275)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:334)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:687)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:633)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:658)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1323)
	at java.net.URL.openStream(URL.java:1037)
	at com.jcabi.xml.TextResource.readAsString(TextResource.java:148)
	at com.jcabi.xml.TextResource.<init>(TextResource.java:102)
	at com.jcabi.xml.XSDDocument.<init>(XSDDocument.java:98)
	at com.qulice.xml.XmlValidator.validate(XmlValidator.java:78)
	... 24 more
```

**Comment by carlosmiranda** [comment]
Pull request created in #375.

**Comment by carlosmiranda** [comment]
@krzyk This should be fixed in #375, can we close the issue now?

**Comment by krzyk** [comment]
thanks

**Comment by davvd** [comment]
once `280-4ce4d8c5` puzzle is resolved, this ticket will be complete

**Comment by davvd** [comment]
@carlosmiranda Many thanks! **30 mins** were added to your account in Transaction ID `50571113`. +30 added to your rating, at the moment it is: [+1815](http://www.netbout.com/b/35023?open=rating)
