### ISSUE TITLE
FindBugs crashes with Java8

### ISSUE THREAD

**Issue by yegor256** [teamed/qulice#379]
This is how it looks:

```
[INFO] /src/it/settings.xml: skipped
[INFO] /src/site/site.xml: to be validated
[INFO] jcabi-aspects 0.17.1/8b0e260 started new daemon thread jcabi-loggable for watching of @Loggable annotated methods
[INFO] JSR-303 validator org.hibernate.validator.internal.engine.ValidatorImpl instantiated by jcabi-aspects 0.17.1/8b0e260
CodeNarc completed: (p1=0; p2=0; p3=0) 19433ms
[INFO] CodeNarc validated 1 file(s)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:48 min
[INFO] Finished at: 2015-01-13T16:14:47-05:00
[INFO] Final Memory: 119M/299M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.11:check (jcabi-check) on project xockets-hadoop-transport: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.11:check failed: Non-zero exit code 1: -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.11:check (jcabi-check) on project xockets-hadoop-transport: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.11:check failed: Non-zero exit code 1: 
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution jcabi-check of goal com.qulice:qulice-maven-plugin:0.11:check failed: Non-zero exit code 1: 
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: java.lang.IllegalArgumentException: Non-zero exit code 1: 
    at com.jcabi.log.VerboseProcess.stdout(VerboseProcess.java:220)
    at com.jcabi.log.VerboseProcess.stdout(VerboseProcess.java:158)
    at com.qulice.findbugs.FindBugsValidator.findbugs(FindBugsValidator.java:114)
    at com.qulice.findbugs.FindBugsValidator.validate(FindBugsValidator.java:83)
    at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
    at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
    at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
    ... 20 more
```

**Comment by davvd** [comment]
this task will get someone's attention soon

**Comment by davvd** [comment]
@oruam85 please go ahead with this task, it's yours

**Comment by davvd** [comment]
@yegor256 thanks for tis bug, I topped your account for 15 mins, transaction `000-485eadcc`

**Comment by oruam85** [comment]
@davvd Please find to someone else for this issue

**Comment by davvd** [comment]
> @davvd Please find to someone else for this issue

@oruam85 I'll ask somebody else to pick this up

**Comment by davvd** [comment]
@dpisarenko it's yours, please go ahead

**Comment by dpisarenko** [comment]
@davvd Please assign someone else to this task, I can't reproduce the error on my machine.

**Comment by davvd** [comment]
> @davvd Please assign someone else to this task, I can't reproduce the error on my machine.

@dpisarenko got it, someone else will be assigned soon

**Comment by longtimeago** [comment]
@yegor256 this issue appears only when old qulice version is used (<0.12)

**Comment by yegor256** [comment]
@longtimeago got it, closing, thanks
