### ISSUE TITLE
Build failed with message "Caused by: java.io.IOException: Cannot run program "javac": CreateProcess error=2"

### ISSUE THREAD

**Issue by apocarteres** [teamed/qulice#394]
<pre>
Tests run: 4, Failures: 0, Errors: 2, Skipped: 1, Time elapsed: 3.979 sec <<< FAILURE! - in com.qulice.findbugs.FindBugs
ValidatorTest
throwsExceptionOnViolation(com.qulice.findbugs.FindBugsValidatorTest)  Time elapsed: 0.14 sec  <<< ERROR!
java.lang.Exception: Unexpected exception, expected<com.qulice.spi.ValidationException> but was<java.io.IOException>
        at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:28)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "javac": CreateProcess error=2, ?? ??????? ????? ????????? ????
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at com.qulice.findbugs.BytecodeMocker.mock(BytecodeMocker.java:77)
        at com.qulice.findbugs.FindBugsValidatorTest.throwsExceptionOnViolation(FindBugsValidatorTest.java:63)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
        ... 10 more
Caused by: java.io.IOException: CreateProcess error=2, ?? ??????? ????? ????????? ????
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
        at java.lang.ProcessImpl.start(ProcessImpl.java:136)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 21 more

excludesIncorrectClassFormCheck(com.qulice.findbugs.FindBugsValidatorTest)  Time elapsed: 0.13 sec  <<< ERROR!
java.io.IOException: Cannot run program "javac": CreateProcess error=2, ?? ??????? ????? ????????? ????
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
        at com.qulice.findbugs.BytecodeMocker.mock(BytecodeMocker.java:77)
        at com.qulice.findbugs.FindBugsValidatorTest.excludesIncorrectClassFormCheck(FindBugsValidatorTest.java:78)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: CreateProcess error=2, ?? ??????? ????? ????????? ????
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(ProcessImpl.java:385)
        at java.lang.ProcessImpl.start(ProcessImpl.java:136)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
        ... 20 more

Results :

Tests in error:
  FindBugsValidatorTest.throwsExceptionOnViolation ╗  Unexpected exception, expe...
  FindBugsValidatorTest.excludesIncorrectClassFormCheck:78 ╗ IO Cannot run progr...

Tests run: 4, Failures: 0, Errors: 2, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................. SUCCESS [  6.830 s]
[INFO] qulice-spi ......................................... SUCCESS [ 15.182 s]
[INFO] qulice-checkstyle .................................. SUCCESS [ 34.233 s]
[INFO] qulice-pmd ......................................... SUCCESS [ 13.295 s]
[INFO] qulice-codenarc .................................... SUCCESS [ 29.907 s]
[INFO] qulice-findbugs .................................... FAILURE [  5.625 s]
[INFO] qulice-xml ......................................... SKIPPED
[INFO] qulice-ant ......................................... SKIPPED
[INFO] qulice-maven-plugin ................................ SKIPPED
[INFO] qulice-gradle-plugin ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:46 min
[INFO] Finished at: 2015-01-28T18:44:55+03:00
[INFO] Final Memory: 56M/494M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project qulice
-findbugs: There are test failures.
[ERROR]
[ERROR] Please refer to Z:\qulice\qulice-findbugs\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-surefire-p
lugin:2.17:test (default-test) on project qulice-findbugs: There are test failures.
</pre>

1. Windows 7 Rus clean install
2. Maven 3.2+
3. Oracle JDK 7
4. <pre>mvn -e clean install -Pqulice</pre>

**Comment by apocarteres** [comment]
looks like user name in Russian locale is a culprit
<pre>
C:\Users\19E8~1\AppData\Local\Temp\1422470323789-1
</pre>
actual username is "кондратка" but path contains something crazy "19E8~1"
that's why process builder returns error status 2 - no such file

**Comment by yegor256** [comment]
@apocarteres how can I reproduce the problem?

**Comment by apocarteres** [comment]
@yegor256 i described it in the end of first message
>>
Windows 7 Rus clean install
Maven 3.2+
Oracle JDK 7
clean checkout of master
<pre>mvn -e clean install -Pqulice</pre>

**Comment by apocarteres** [comment]
ok i figured out. Username doesn't affect build. 
The problem is that ProcessBuilder can't find <code>javac</code> executable.
<code>com.qulice.findbugs.BytecodeMocker</code> at the line 74
<pre>
        final ProcessBuilder builder = new ProcessBuilder(
            "javac",
            "-d",
            outdir.getPath(),
            input.getPath()
        );
</pre>

looks like it's connected with environments varibales, since i hacked it a little bit to
<pre>
        final ProcessBuilder builder = new ProcessBuilder(
            "C:\\Program Files\\Java\\jdk1.7.0_75\\bin\\javac.exe",
            "-d",
            outdir.getPath(),
            input.getPath()
        );
</pre>

and it works well

**Comment by yegor256** [comment]
@apocarteres but Appveyor builds everything without problems. Looks like it's your local problem, don't you think?

**Comment by apocarteres** [comment]
@yegor256 Appveyor uses win2k and EN locale. Probably it's may be a corner. I have clean local win7 installation, several other projects jcabi* build well there. Not sure that's local problem

**Comment by yegor256** [comment]
@apocarteres do you have any suggestion how this may be fixed? As I see, Windows gives us a wrong path.. We just can't do anything about it, inside our plugin. But maybe I'm wrong.

**Comment by apocarteres** [comment]
@yegor256 i think the root cause is connected with passing environments variables between components of application. it should be debugged to say what's is happening there.

**Comment by yegor256** [comment]
@apocarteres Look at this:

```
C:\Users\19E8~1\AppData\Local\Temp\1422470323789-1
```

This `19E8~1` can't generated by our plugin. It's coming from operating system.

**Comment by apocarteres** [comment]
@yegor256 correct. but it's not an issue. the problem is that <code>javac</code> can't be found in <code>com.qulice.findbugs.BytecodeMocker</code> line 71

**Comment by apocarteres** [comment]
as mentioned above

the hack
<pre>
final ProcessBuilder builder = new ProcessBuilder(
            "C:\\Program Files\\Java\\jdk1.7.0_75\\bin\\javac.exe",
            "-d",
            outdir.getPath(),
            input.getPath()
        );
</pre>
get build work

**Comment by davvd** [comment]
@nhekfqn the task is yours plz proceed

**Comment by davvd** [comment]
@apocarteres thanks a lot for reporting, **15 mins** added to your acc, pmt ID `50954585`

**Comment by palyuga** [comment]
@yegor256 It's duplication of #380
Happens when `javac` not in `PATH`

**Comment by apocarteres** [comment]
@palyuga don't think so. pls take a look at screenshots
![screen shot 2015-01-30 at 11 43 20 am](https://cloud.githubusercontent.com/assets/3305624/5973088/45b3894c-a875-11e4-9ec0-d9acc566cf34.png)
![screen shot 2015-01-30 at 11 43 01 am](https://cloud.githubusercontent.com/assets/3305624/5973089/45b40c5a-a875-11e4-8ea2-c35a6fbb91cb.png)
![screen shot 2015-01-30 at 11 42 44 am](https://cloud.githubusercontent.com/assets/3305624/5973087/45b34fb8-a875-11e4-925c-cef7c045c030.png)

**Comment by apocarteres** [comment]
@palyuga furthermore the code
<pre>
public class Test {
    public static void main(String[] argv) throws java.lang.Exception {
        final ProcessBuilder builder = new ProcessBuilder(
            "javac",
            "-d",
            "C:\\Users\\19E8~1\\AppData\\Local\\Temp\\",
            "Foo.java"
        );
	    Process p  = builder.start();
	    p.waitFor();
    }
}
</pre>
works well

**Comment by palyuga** [comment]
@apocarteres yep, I was wrong then, it's not a duplication)

**Comment by nhekfqn** [comment]
@davvd Please find someone else to do this task.

**Comment by davvd** [comment]
> @davvd Please find someone else to do this task.

@nhekfqn someone else will help in this task, no problem at all

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk someone else will help in this task, no problem at all

**Comment by yegor256** [comment]
@apocarteres this seems to be resolved. if not, please submit a new issue
