### ISSUE TITLE
URISyntaxException

### ISSUE THREAD

**Issue by maurezen** [teamed/qulice#397]
In `DefaultMavenEnvironment#classLoader` there is a following code:
```java
    urls.add(
        URI.create(String.format("file:///%s", path)).toURL()
    );
```
It gets executed for each entry in `this,classpath()`. If any entry contains space, this results in `URISyntaxException`. 
A simple example of how this happens here jcabi/jcabi-xml#49 - Windows, maven repo in Documents and Settings folder, maven artifacts in classpath.
Relevant part of the log:
>`Caused by: java.lang.IllegalArgumentException: Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/reposito
ry/com/jcabi/jcabi-aspects/0.20.1/jcabi-aspects-0.20.1.jar
        at java.net.URI.create(URI.java:859)
        at com.qulice.maven.DefaultMavenEnvironment.classloader(DefaultMavenEnvironment.java:152)
        at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:81)
        at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
        at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
        at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
Caused by: java.net.URISyntaxException: Illegal character in path at index 19: file://C:/Documents and Settings/JustUser/.m2/repository/com/
jcabi/jcabi-aspects/0.20.1/jcabi-aspects-0.20.1.jar
        at java.net.URI$Parser.fail(URI.java:2829)
        at java.net.URI$Parser.checkChars(URI.java:3002)
        at java.net.URI$Parser.parseHierarchical(URI.java:3086)
        at java.net.URI$Parser.parse(URI.java:3034)
        at java.net.URI.(URI.java:595)
        at java.net.URI.create(URI.java:857)
        ... 26 more`

Suggested way of fixing it is using `File#toURI` instead of `new URI(String)`.

**Comment by davvd** [comment]
this task will get someone's attention soon

**Comment by davvd** [comment]
@maurezen many thanks for the bug report, I added 15 mins to your acc, transaction `51289193`

**Comment by davvd** [comment]
@krzyk it's yours, budget is 30 mins, please go ahead

**Comment by krzyk** [comment]
@maurezen strange, this looks like #243

**Comment by krzyk** [comment]
@maurezen the lines reported in the original issue don't match with current qulice release, it looks like jcabi-xml is using qulice < 0.8.2

**Comment by krzyk** [comment]
@maurezen ping

**Comment by krzyk** [comment]
@alex-palevsky please give me more time here

**Comment by krzyk** [comment]
@maurezen if the explanations is enought please close this issue

**Comment by maurezen** [comment]
@krzyk at the moment jcabi-xml uses jcabi v 1.17, which uses parent 0.32.1, which uses qulice 0.12. At qulice's master branch the code is exactly as I've described, though the `URI.create()` call moved to the line number 159.

**Comment by krzyk** [comment]
@maurezen strange, because there is explicit case for spaces in the URL, so this must be some other case. Do you have the full stack trace and the URL for which it fails?

**Comment by krzyk** [comment]
@maurezen ping

**Comment by krzyk** [comment]
@maurezen and ping again

**Comment by krzyk** [comment]
@maurezen ping

**Comment by krzyk** [comment]
@maurezen help me out here, please

**Comment by krzyk** [comment]
@maurezen any news?

**Comment by maurezen** [comment]
@krzyk uh. sorry, was distracted. I will take a look at this.

**Comment by maurezen** [comment]
@krzyk failed to reproduce it. thanks for your effort!

**Comment by davvd** [comment]
@krzyk Thanks a lot, I just topped your account for **38 mins**, transaction ID `60333857`, total time was 2165 hours and 56 mins... there is a bonus for fast delivery (age=2924)... +38 added to your rating, at the moment it is: [+4522](http://www.netbout.com/b/35035?open=rating)
