### ISSUE TITLE
ArrayIndexOutOfBoundsException in ImportCohesionCheck on file with imports only

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#451]
I get the following exception while doing analysis of Checkstyle project:

```
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.12.1:check (default-cli) on project checkstyle: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.12.1:check failed: 8 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.12.1:check (default-cli) on project checkstyle: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.12.1:check failed: 8
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.12.1:check failed: 8
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 8
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:346)
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:54)
	at com.qulice.checkstyle.ImportCohesionCheck.check(ImportCohesionCheck.java:95)
	at com.qulice.checkstyle.ImportCohesionCheck.processFiltered(ImportCohesionCheck.java:75)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:73)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:263)
	at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:92)
	at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
	at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

Do you need anything else to reproduce?

**Comment by davvd** [comment]
@yegor256 please do something about this issue

**Comment by yegor256** [comment]
@mkordas would be great to see your `.java` file where it crashes.

**Comment by krzyk** [comment]
@mkordas Could you add an example java file that causes this crash?

**Comment by mkordas** [comment]
I don't know the file. Any hints how can I track it? I tried updating to Checkstyle 6.12 which reports problematic filename in stacktraces, but I didn't succeed with building qulice-maven-plugin locally: `java.lang.ClassNotFoundException: com.qulice.spi.Environment`.

**Comment by krzyk** [comment]
@mkordas Maybe we could change this issue into a an upgrade to checkstyle 6.12? We could do a release and then you could check if qulice fails on your code, and if it does you would have the filename?

**Comment by krzyk** [comment]
@mkordas BTW is there an info about filenames in stack traces in Checkstyle realise notes?  I can't find it.

**Comment by mkordas** [comment]
@krzyk 
I think we can just create another issue to upgrade Checkstyle: #487

There is note about additional logging in [release notes](http://checkstyle.sourceforge.net/releasenotes.html#Release_6.12):
* CLI should print a file name where exception is happen. Author: Roman Ivanov checkstyle/checkstyle#2109

**Comment by krzyk** [comment]
@mkordas But until the checkstyle is upgraded this issue is not valid, without an example we don't know where is the problem.

**Comment by mkordas** [comment]
OK, so I'm closing it.

**Comment by mkordas** [comment]
I've managed to build Qulice with Checkstyle 6.12 locally (although I needed to do `mvn install -Dmaven.test.skip=true install -Dinvoker.skip=true` because tests were failing in my Windows environment) and here's nice end of stacktrace:
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\resources\Reproducer.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:89)
	... 31 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 3
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:324)
	at com.puppycrawl.tools.checkstyle.api.FileText.get(FileText.java:58)
	at com.qulice.checkstyle.ImportCohesionCheck.check(ImportCohesionCheck.java:95)
	at com.qulice.checkstyle.ImportCohesionCheck.processFiltered(ImportCohesionCheck.java:75)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 32 more
```

Minimal reproducer:
```java
package com.google;

import java.util.*;
```

Note: this is valid and compilable Java file.

**Comment by krzyk** [comment]
@mkordas interesting case,  thanks

**Comment by krzyk** [comment]
@mkordas could you add a he code above to the issue description? It will be easier to find.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by mkordas** [comment]
> @mkordas could you add a he code above to the issue description? It will be easier to find.

@krzyk, is it fine now?

**Comment by krzyk** [comment]
@mkordas yes, thanks

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk OK, I put "postponed" label here

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk no problem, I will try to find somebody else

**Comment by davvd** [comment]
@mkordas thanks for this report, I added 15 mins to your account, in transaction `566830ec6d5fb6522c0000c9`

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@HDouss want to take this?

**Comment by HDouss** [comment]
@krzyk Yes please.

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk sure, thanks, I removed "postponed" tag to it

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk done. @hdouss the task is yours, please go ahead

**Comment by HDouss** [comment]
@mkordas The minimal reproducer here would fail because of `NewlineAtEndOfFileCheck`. That means I cannot add a unit test to make it pass. It won't pass anyway.

**Comment by mkordas** [comment]
@HDouss can't you just add newline at the end of file but still keep just imports?

**Comment by HDouss** [comment]
@mkordas Do you reproduce ArrayIndexOutOfBoundsException in ImportCohesionCheck  for such a file ?

**Comment by mkordas** [comment]
@HDouss In August it was reproducible for me, I don't remember exactly how :) We just need any test case for the issue.

**Comment by HDouss** [comment]
@mkordas PR #626 reviewed and merged. Please close the issue.

**Comment by mkordas** [comment]
@HDouss thanks!

**Comment by davvd** [comment]
@hdouss Much obliged! I have added **30 mins** to your account in payment "75231569", 72 hours and 20 mins spent

+30 to your rating, your total score is [+1352](http://www.netbout.com/b/36032?open=rating)
