### ISSUE TITLE
qulice-maven-plugin 0.12: Build failure with ValidationException

### ISSUE THREAD

**Issue by simonjenga** [teamed/qulice#482]
```
[INFO]
[INFO] --- qulice-maven-plugin:0.12:check (jcabi-check) @ qulice-spi ---
[INFO] LICENSE found: file:C:/javaworkspace/qulice/qulice-spi/LICENSE.txt
[INFO] No Checkstyle violations found in 8 files
[INFO] No PMD violations found in 6 files
[INFO] \src\site\site.xml: to be validated
[WARNING] 3 XML validation error(s):
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
  -1:-1: cvc-elt.1: Cannot find the declaration of element 'project'.
  -1:-1: schema_reference.4: Failed to read schema document 'http://maven.apache.org/xsd/decoration-1.3.0.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.
<?xml version="1.0" encoding="UTF-8"?>
<!--
 * Copyright (c) 2011-2015, Qulice.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met: 1) Redistributions of source code must retain the above
 * copyright notice, this list of conditions and the following
 * disclaimer. 2) Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following
 * disclaimer in the documentation and/or other materials provided
 * with the distribution. 3) Neither the name of the Qulice.com nor
 * the names of its contributors may be used to endorse or promote
 * products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 --><project xmlns="http://maven.apache.org/DECORATION/1.3.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         name="qulice-spi"
         xsi:schemaLocation="http://maven.apache.org/DECORATION/1.3.0 http://maven.apache.org/xsd/decoration-1.3.0.xsd">
    <body>
        <menu ref="parent"/>
        <menu name="Overview">
            <item href="index.html" name="Introduction"/>
        </menu>
        <menu ref="reports"/>
    </body>
</project>
[INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................ SUCCESS [9.550s]
[INFO] qulice-spi ........................................ FAILURE [1:00.996s]
[INFO] qulice-checkstyle ................................. SKIPPED
[INFO] qulice-pmd ........................................ SKIPPED
[INFO] qulice-codenarc ................................... SKIPPED
[INFO] qulice-findbugs ................................... SKIPPED
[INFO] qulice-xml ........................................ SKIPPED
[INFO] qulice-ant ........................................ SKIPPED
[INFO] qulice-maven-plugin ............................... SKIPPED
[INFO] qulice-gradle-plugin .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.12:check (jcabi-check) on project qulice-spi: Failure: java.lang.IllegalArgumentException: 3 error(s), see log above -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.12:check (jcabi-check) on project qulice-spi: Failure
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:317)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:152)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:555)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:214)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Failure
        at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:65)
        at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: com.qulice.spi.ValidationException: java.lang.IllegalArgumentException: 3 error(s), see log above
        at com.qulice.xml.XmlValidator.validate(XmlValidator.java:109)
        at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
        at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
        ... 22 more
Caused by: java.lang.IllegalArgumentException: 3 error(s), see log above
        at com.jcabi.xml.StrictXML.<init>(StrictXML.java:105)
        at com.qulice.xml.XmlValidator.validate(XmlValidator.java:95)
        ... 24 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :qulice-spi
```

**Comment by davvd** [comment]
@yegor256 take a look at this issue please and dispatch it somehow, see [par.21](http://www.teamed.io/policy.html#21)

**Comment by yegor256** [comment]
@simonjenga how can I reproduce it? The build is clean on Travis and on my machine:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................. SUCCESS [  2.677 s]
[INFO] qulice-spi ......................................... SUCCESS [  5.591 s]
[INFO] qulice-checkstyle .................................. SUCCESS [ 10.382 s]
[INFO] qulice-pmd ......................................... SUCCESS [  8.185 s]
[INFO] qulice-codenarc .................................... SUCCESS [  7.283 s]
[INFO] qulice-findbugs .................................... SUCCESS [  7.851 s]
[INFO] qulice-xml ......................................... SUCCESS [  3.990 s]
[INFO] qulice-ant ......................................... SUCCESS [ 15.230 s]
[INFO] qulice-maven-plugin ................................ SUCCESS [01:21 min]
[INFO] qulice-gradle-plugin ............................... SUCCESS [  0.783 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:23 min
[INFO] Finished at: 2015-10-26T10:07:20-07:00
[INFO] Final Memory: 151M/931M
[INFO] ------------------------------------------------------------------------
```

**Comment by krzyk** [comment]
@simonjenga from the logs you provided it looks like a network issue - maybe your network connection was down, or maybe you are behind a proxy or maven.apache.org was down

**Comment by simonjenga** [comment]
@yegor256 @krzyk You're right, it was a problem with my network connection during that day when i was executing the build. The project now builds OK.
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................ SUCCESS [6.278s]
[INFO] qulice-spi ........................................ SUCCESS [9.548s]
[INFO] qulice-checkstyle ................................. SUCCESS [17.095s]
[INFO] qulice-pmd ........................................ SUCCESS [10.615s]
[INFO] qulice-codenarc ................................... SUCCESS [9.340s]
[INFO] qulice-findbugs ................................... SUCCESS [5.484s]
[INFO] qulice-xml ........................................ SUCCESS [6.804s]
[INFO] qulice-ant ........................................ SUCCESS [13.568s]
[INFO] qulice-maven-plugin ............................... SUCCESS [28.643s]
[INFO] qulice-gradle-plugin .............................. SUCCESS [1.637s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

Am now closing this issue, Thnx!
