### ISSUE TITLE
NPE in BracketsStructure check

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#489]
Stacktrace:
```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing src\test\resources\Reproducer.java
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:282)
	at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:89)
	... 31 more
Caused by: java.lang.NullPointerException
	at com.qulice.checkstyle.BracketsStructureCheck.checkLines(BracketsStructureCheck.java:112)
	at com.qulice.checkstyle.BracketsStructureCheck.checkParams(BracketsStructureCheck.java:93)
	at com.qulice.checkstyle.BracketsStructureCheck.visitToken(BracketsStructureCheck.java:77)
	at com.puppycrawl.tools.checkstyle.TreeWalker.notifyVisit(TreeWalker.java:390)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processIter(TreeWalker.java:501)
	at com.puppycrawl.tools.checkstyle.TreeWalker.walk(TreeWalker.java:332)
	at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:204)
	at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:79)
	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:266)
	... 32 more
```

Minimal reproducer:
```java
class Reproducer {
    void run() {
        Object anon2 = new
                Object() {};
    }
}

```

**Comment by krzyk** [comment]
@mkordas thanks

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk all right, we'll find someone else for this task

**Comment by mkordas** [comment]
@davvd I can take this one

**Comment by krzyk** [comment]
@mkordas generally it is not a good idea for bug reported and fixer to be the same person (it reduces the number of persons that check the fix).
If you would like to help out, there are a couple of bugs that need fixing for the next release, e.g. #424 #477

**Comment by mkordas** [comment]
@krzyk 
Agreed, I won't be fixing my issues anymore, I'll look into others.

**Comment by krzyk** [comment]
@davvd please assign @mkordas

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by davvd** [comment]
> @davvd please assign @mkordas 

@krzyk @mkordas is not in our team, we can't assign a ticket to him. just let him fix it and that's it

**Comment by davvd** [comment]
> @davvd this is not postponed 

@krzyk right, I removed "postponed" tag

**Comment by krzyk** [comment]
@mkordas your changes have been merged to master, so you can close this issue

**Comment by mkordas** [comment]
@krzyk I'm closing the issue. BTW, how can I join your team?

**Comment by krzyk** [comment]
@mkordas here http://at.teamed.io/join.html

**Comment by mkordas** [comment]
@yegor256 can I get payment for issue submission and implementation here?

**Comment by yegor256** [comment]
@mkordas you were not with us that time :) so, no payment, sorry
