### ISSUE TITLE
XML validator fails with NPE

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#498]
Maven build failed if following xml is not excluded from check:
```xml
<!--
 * Copyright (c) 2012-2015, jcabi.com
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met: 1) Redistributions of source code must retain the above
 * copyright notice, this list of conditions and the following
 * disclaimer. 2) Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following
 * disclaimer in the documentation and/or other materials provided
 * with the distribution. 3) Neither the name of the jcabi.com nor
 * the names of its contributors may be used to endorse or promote
 * products derived from this software without specific prior written
 * permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL
 * THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 -->
<Configuration>
    <Appenders>
        <Console name="CONSOLE" target="SYSTEM_OUT">
            <PatternLayout pattern="[%p] %t %c: %m%n"/>
        </Console>
    </Appenders>
    <Loggers>
        <Logger name="org.apache.log4j.xml" level="ERROR"/>
        <Root level="WARN">
            <AppenderRef ref="CONSOLE"/>
        </Root>
    </Loggers>
</Configuration>
```
Here is full exception
```
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.13:check (default-cli) on project jcabi: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.13:check failed. NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.13:check (default-cli) on project jcabi: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.13:check failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.13:check failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at sun.misc.MetaIndex.mayContain(MetaIndex.java:243)
	at sun.misc.URLClassPath$JarLoader.getResource(URLClassPath.java:830)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:199)
	at sun.misc.URLClassPath.getResource(URLClassPath.java:251)
	at java.lang.ClassLoader.getBootstrapResource(ClassLoader.java:1305)
	at java.lang.ClassLoader.getResource(ClassLoader.java:1144)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.getResource(ClassRealm.java:275)
	at java.net.URLClassLoader.getResourceAsStream(URLClassLoader.java:227)
	at java.lang.Class.getResourceAsStream(Class.java:2111)
	at com.jcabi.xml.ClasspathResolver.resolveResource(ClasspathResolver.java:54)
	at com.sun.org.apache.xerces.internal.util.DOMEntityResolverWrapper.resolveEntity(DOMEntityResolverWrapper.java:109)
	at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.resolveEntity(XMLEntityManager.java:1076)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.resolveDocument(XMLSchemaLoader.java:660)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2436)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1772)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:746)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.beginNode(DOMValidatorHelper.java:277)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:244)
	at com.sun.org.apache.xerces.internal.jaxp.validation.DOMValidatorHelper.validate(DOMValidatorHelper.java:190)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:109)
	at javax.xml.validation.Validator.validate(Validator.java:124)
	at com.jcabi.xml.StrictXML.validate(StrictXML.java:217)
	at com.jcabi.xml.StrictXML.<init>(StrictXML.java:86)
	at com.qulice.xml.XmlValidator.validate(XmlValidator.java:98)
	at com.qulice.maven.CheckMojo.run(CheckMojo.java:83)
	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
	at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 20 more
```
```
$ mvn --v
Apache Maven 3.2.1 (ea8b2b07643dbb1b84b6d16e1f08391b666bc1e9; 2014-02-14T19:37:52+02:00)
Maven home: /devtools/maven
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-30-generic", arch: "amd64", family: "unix"
```
Checked on qulice-maven-plugin:0.13 and 0.13.1

**Comment by longtimeago** [comment]
Oh, looks like this was fixed in qulice-maven-plugin:0.13.1

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk thanks, I added "postponed" label

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk right, I'll try to find someone else for this task

**Comment by davvd** [comment]
@longtimeago thanks for reporting! I topped your account for 15 mins, transaction 70524570

**Comment by krzyk** [comment]
@davvd this is not postponed

**Comment by krzyk** [comment]
@aschworer can you work on this?

**Comment by aschworer** [comment]
@krzyk I'm afraid I can only have 2 concurrent tasks at a time

**Comment by davvd** [comment]
> @davvd this is not postponed

@krzyk right, I removed "postponed" tag

**Comment by krzyk** [comment]
@davvd assign @Happy-Neko please

**Comment by davvd** [comment]
> @davvd assign @Happy-Neko please

@krzyk done. @happy-neko you are assigned to this task. please proceed...

**Comment by krzyk** [comment]
@Happy-Neko how is the task going do you need any help?

**Comment by Happy-Neko** [comment]
@krzyk missed the original email. Will look into this. Thanks.

**Comment by krzyk** [comment]
@longtimeago changes have been merged in #570, please close if this resolves the issue
@Happy-Neko sorry for cutting in, but I would like to release 0.15, and this one is blocking it

**Comment by longtimeago** [comment]
@krzyk thanks!

**Comment by davvd** [comment]
@happy-neko paid, thanks, added **30 mins** to your account, payment `74128224`, 263 hours and 9 mins was spent... +30 to your rating, your total score is [+8](http://www.netbout.com/b/36136?open=rating)
