### ISSUE TITLE
Cannot run Qulice twice on the same project without 'clean'

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#510]
To reproduce the issue create simplest possible Maven project (e.g. using `mvn archetype:generate`)  with standard Qulice config and run the build twice without `clean`:
```
mvn verify
mvn verify
```
Stacktrace:
```
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.14:check (default) on project any: Execution default of goal com.qulice:qulice-maven-plugin:0.14:check failed: Unable to crate directories needed for C:\IdeaProjects\repro\target\classes\checkstyle\checkstyle.cache
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal com.qulice:qulice-maven-plugin:0.14:check failed: Unable to crate directories needed for C:\IdeaProjects\repro\target\classes\checkstyle\checkstyle.cache
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:143)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: java.lang.IllegalStateException: Unable to crate directories needed for C:\IdeaProjects\repro\target\classes\checkstyle\checkstyle.cache
        at com.qulice.checkstyle.CheckstyleValidator.configuration(CheckstyleValidator.java:122)
        at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:82)
        at com.qulice.maven.CheckMojo.run(CheckMojo.java:84)
        at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
        at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
        ... 20 more
```

**Comment by krzyk** [comment]
@mkordas qulice needs compiled artifacts to perform it's job (e.g. Findbugs needs them), so the validate phase is too early for it.

**Comment by mkordas** [comment]
@krzyk you are right, but the issue doesn't depend on Maven phase invoked. `validate` is quickest way to reproduce (no need to compile anything), but it occurs also when calling `verify`. I've updated issue description accordingly.

**Comment by krzyk** [comment]
@mkordas you are right

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by davvd** [comment]
@mkordas many thanks for the report, I topped your account for 15 mins, transaction 566ffb8190f2e30082000199

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk done. @hdouss you are assigned to this task. please proceed...

**Comment by HDouss** [comment]
@mkordas PR #557 merged. Please close the issue

**Comment by mkordas** [comment]
@HDouss thanks!

**Comment by HDouss** [comment]
@davvd Issue closed

**Comment by davvd** [comment]
@hdouss paid, thanks, added **1 hour** to your account, payment `73491744`, 23 hours and 44 mins was spent... there is a bonus for fast delivery (m=1424)... +60 added to your rating, current score is: [+451](http://www.netbout.com/b/36032?open=rating)

**Comment by longtimeago** [comment]
@krzyk please, release new version of qulice plugin. This bug is really annoying

**Comment by krzyk** [comment]
@longtimeago `0.14.2` has the fix
