### ISSUE TITLE
POM and README do not specify minimal Maven version as 3.1.0

### ISSUE THREAD

**Issue by mkordas** [teamed/qulice#514]
On Maven 3.0.5 (which is default version bundled in IntelliJ and Linux) build fails with the following exception:
```
ERROR] Internal error: java.lang.NullPointerException -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.NullPointerException
	at org.apache.maven.lifecycle.internal.BuilderCommon.handleBuildError(BuilderCommon.java:128)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:95)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.NullPointerException
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromChildren(CollectionConverter.java:157)
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:112)
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:289)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:161)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:567)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:529)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	... 22 more
```
This happens due to bug in Maven that was fixed in 3.1.0. To save people's time when they try to debug NPE, POM should enforce 3.1.0 as minimal Maven version to build Qulice. Moreover, README should contain this requirement too.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I added `bug` tag to this ticket

**Comment by davvd** [comment]
@mkordas thank you for reporting this, I added 15 mins to your acc, transaction `566ebb1c9605e3655700036c`

**Comment by HDouss** [comment]
@krzyk Please assign this issue to me.

**Comment by krzyk** [comment]
@davvd assign @HDouss please

**Comment by davvd** [comment]
> @davvd assign @HDouss please

@krzyk OK @hdouss please start, the task is yours

**Comment by HDouss** [comment]
@mkordas seems like minimal version to have is 3.2 (see #439 ). Do you agree ?

**Comment by mkordas** [comment]
@HDouss what build error do you get on 3.1.0?

**Comment by HDouss** [comment]
@mkordas I don't have the NPE error with 3.1.0. I was wondering if I have to take into consideration issue #439 (seems like a duplicate of this one). So you are right, my PR will deal with 3.1.0 as the required Maven version.

PS : I still think #439 is a duplicate of this one, just that the reported minimal version there is wrong

**Comment by mkordas** [comment]
@HDouss  If we confirm somehow that Qulice build works perfectly fine on 3.1.0 both on Linux and Windows we can just mark #439 as invalid.

**Comment by HDouss** [comment]
@mkordas I agree. I think it is the case.

**Comment by krzyk** [comment]
@HDouss please add reference to the PR in the issue messages (so all interested can look at it, before the review, or even after the issue was closed)

**Comment by HDouss** [comment]
@krzyk I usually do it when asking the author to close the issue like in the upcoming comment.

**Comment by krzyk** [comment]
@HDouss OK

**Comment by HDouss** [comment]
@mkordas PR #516 reviewed and merged. Please close the issue.

**Comment by mkordas** [comment]
@HDouss accepted, looks really good

**Comment by davvd** [comment]
@hdouss **38 mins** sent to your balance (ID `72451345`), many thanks! It took 49 hours and 17 mins.. the bonus for fast delivery (m=2957). +38 added to your rating, current score is: [+188](http://www.netbout.com/b/36032?open=rating)

**Comment by HDouss** [comment]
@davvd  According to the Definition of Done, the issue is done when the author accepts the delivrables and closes the issue. The issue was assigned to me on Dec 15 7:48 AM (GMT). The issue was closed on Dec 16 2:50 PM (GMT). This is less than 48h, so I was expecting a payment and a rating bonus of 50%. I received a bonus of only 25%.

**Comment by davvd** [comment]
> @davvd  According to the Definition of Done, the issue is done when the author accepts the delivrables and closes the issue. The issue was assigned to me on Dec 15 7:48 AM (GMT). The issue was closed on Dec 16 2:50 PM (GMT). This is less than 48h, so I was expecting a payment and a rating bonus of 50%. I received a bonus of only 25%.

@hdouss this is how we calculate the duration of an issue: http://at.teamed.io/policy.html#15 make sense?

**Comment by HDouss** [comment]
@davvd The rule is somehow unfair. But anyway, thank you for clarifying it to me.

**Comment by davvd** [comment]
> @davvd The rule is somehow unfair. But anyway, thank you for clarifying it to me.

@hdouss no problem
