### ISSUE TITLE
Unable to create directories needed for checkstyle.cache

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#585]
Fail running
```  mvn qulice:check -Pqulice ```
twice in a row with exception (on the second run):
```
[ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:0.14:check (default-cli) on project XHT: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.14:check failed: Unable to crate directories needed for /home/my/pr/XHT/target/classes/checkstyle/checkstyle.cache -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:0.14:check (default-cli) on project XHTt: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.14:check failed: Unable to crate directories needed for /home/my/pr/XHT/target/classes/checkstyle/checkstyle.cache
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.qulice:qulice-maven-plugin:0.14:check failed: Unable to crate directories needed for /home/my/pr/XHT/target/classes/checkstyle/checkstyle.cache
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:144)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.IllegalStateException: Unable to crate directories needed for /home/my/pr/XHT/target/classes/checkstyle/checkstyle.cache
	at com.qulice.checkstyle.CheckstyleValidator.configuration(CheckstyleValidator.java:122)
	at com.qulice.checkstyle.CheckstyleValidator.validate(CheckstyleValidator.java:82)
	at com.qulice.maven.CheckMojo.run(CheckMojo.java:84)
	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:59)
	at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:175)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	... 20 more
```

**Comment by mkordas** [comment]
@longtimeago I've submitted this issue in #510. It's already fixed.

**Comment by longtimeago** [comment]
@mkordas cool, thanks!
