### ISSUE TITLE
CheckstyleValidatorTest fails intermittently

### ISSUE THREAD

**Issue by simonjenga** [teamed/qulice#691]
```
[INFO ] com.qulice.checkstyle.CheckstyleValidator: No Checkstyle violations found in 2 files
Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.551 sec <<< FAILURE! - in com.qulice.checkstyle.CheckstyleValidatorTest
distinguishesValidCatchParameterNames(com.qulice.checkstyle.CheckstyleValidatorTest)  Time elapsed: 0.015 sec  <<< ERROR!
java.lang.IllegalStateException: mkdir failed
        at com.qulice.spi.Environment$Mock.<init>(Environment.java:165)
        at com.qulice.checkstyle.CheckstyleValidatorTest.runValidation(CheckstyleValidatorTest.java:547)
        at com.qulice.checkstyle.CheckstyleValidatorTest.distinguishesValidCatchParameterNames(CheckstyleValidatorTest.java:442)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  CheckstyleValidatorTest.distinguishesValidCatchParameterNames:442->runValidation:547 -+ IllegalState

Tests run: 53, Failures: 0, Errors: 1, Skipped: 0


[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................ SUCCESS [1.030s]
[INFO] qulice-spi ........................................ SUCCESS [3.182s]
[INFO] qulice-checkstyle ................................. FAILURE [19.174s]
[INFO] qulice-pmd ........................................ SKIPPED
[INFO] qulice-codenarc ................................... SKIPPED
[INFO] qulice-findbugs ................................... SKIPPED
[INFO] qulice-xml ........................................ SKIPPED
[INFO] qulice-ant ........................................ SKIPPED
[INFO] qulice-maven-plugin ............................... SKIPPED
[INFO] qulice-gradle-plugin .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

[INFO ] com.qulice.checkstyle.CheckstyleValidator: No Checkstyle violations found in 2 files
Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.676 sec <<< FAILURE! - in com.qulice.checkstyle.CheckstyleValidatorTest
acceptsConstructorParametersNamedJustLikeFields(com.qulice.checkstyle.CheckstyleValidatorTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.IllegalStateException: mkdir failed
        at com.qulice.spi.Environment$Mock.<init>(Environment.java:165)
        at com.qulice.checkstyle.CheckstyleValidatorTest.runValidation(CheckstyleValidatorTest.java:547)
        at com.qulice.checkstyle.CheckstyleValidatorTest.validateCheckstyle(CheckstyleValidatorTest.java:535)
        at com.qulice.checkstyle.CheckstyleValidatorTest.acceptsConstructorParametersNamedJustLikeFields(CheckstyleValidatorTest.java:271)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  CheckstyleValidatorTest.acceptsConstructorParametersNamedJustLikeFields:271->validateCheckstyle:535->runValidation:547 -+ IllegalState

Tests run: 28, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................ SUCCESS [1.045s]
[INFO] qulice-spi ........................................ SUCCESS [3.588s]
[INFO] qulice-checkstyle ................................. FAILURE [20.671s]
[INFO] qulice-pmd ........................................ SKIPPED
[INFO] qulice-codenarc ................................... SKIPPED
[INFO] qulice-findbugs ................................... SKIPPED
[INFO] qulice-xml ........................................ SKIPPED
[INFO] qulice-ant ........................................ SKIPPED
[INFO] qulice-maven-plugin ............................... SKIPPED
[INFO] qulice-gradle-plugin .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

[INFO ] com.qulice.checkstyle.CheckstyleValidator: No Checkstyle violations found in 2 files
Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 17.207 sec <<< FAILURE! - in com.qulice.checkstyle.CheckstyleValidatorTest
acceptsConstantUsedInMethodAnnotation(com.qulice.checkstyle.CheckstyleValidatorTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.IllegalStateException: mkdir failed
        at com.qulice.spi.Environment$Mock.<init>(Environment.java:165)
        at com.qulice.checkstyle.CheckstyleValidatorTest.runValidation(CheckstyleValidatorTest.java:547)
        at com.qulice.checkstyle.CheckstyleValidatorTest.validateCheckstyle(CheckstyleValidatorTest.java:535)
        at com.qulice.checkstyle.CheckstyleValidatorTest.acceptsConstantUsedInMethodAnnotation(CheckstyleValidatorTest.java:257)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  CheckstyleValidatorTest.acceptsConstantUsedInMethodAnnotation:257->validateCheckstyle:535->runValidation:547 -+ IllegalState

Tests run: 25, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................ SUCCESS [1.030s]
[INFO] qulice-spi ........................................ SUCCESS [3.245s]
[INFO] qulice-checkstyle ................................. FAILURE [20.827s]
[INFO] qulice-pmd ........................................ SKIPPED
[INFO] qulice-codenarc ................................... SKIPPED
[INFO] qulice-findbugs ................................... SKIPPED
[INFO] qulice-xml ........................................ SKIPPED
[INFO] qulice-ant ........................................ SKIPPED
[INFO] qulice-maven-plugin ............................... SKIPPED
[INFO] qulice-gradle-plugin .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

[INFO ] com.qulice.checkstyle.CheckstyleValidator: No Checkstyle violations found in 2 files
Tests run: 23, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 16.926 sec <<< FAILURE! - in com.qulice.checkstyle.CheckstyleValidatorTest
allowsOnlyProperlyNamedLocalVariables(com.qulice.checkstyle.CheckstyleValidatorTest)  Time elapsed: 0.031 sec  <<< ERROR!
java.lang.IllegalStateException: mkdir failed
        at com.qulice.spi.Environment$Mock.<init>(Environment.java:165)
        at com.qulice.checkstyle.CheckstyleValidatorTest.runValidation(CheckstyleValidatorTest.java:547)
        at com.qulice.checkstyle.CheckstyleValidatorTest.allowsOnlyProperlyNamedLocalVariables(CheckstyleValidatorTest.java:294)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.rules.RunRules.evaluate(RunRules.java:20)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  CheckstyleValidatorTest.allowsOnlyProperlyNamedLocalVariables:294->runValidation:547 -+ IllegalState

Tests run: 29, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................ SUCCESS [1.029s]
[INFO] qulice-spi ........................................ SUCCESS [3.245s]
[INFO] qulice-checkstyle ................................. FAILURE [19.626s]
[INFO] qulice-pmd ........................................ SKIPPED
[INFO] qulice-codenarc ................................... SKIPPED
[INFO] qulice-findbugs ................................... SKIPPED
[INFO] qulice-xml ........................................ SKIPPED
[INFO] qulice-ant ........................................ SKIPPED
[INFO] qulice-maven-plugin ............................... SKIPPED
[INFO] qulice-gradle-plugin .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by krzyk** [comment]
@simonjenga strange, do you have space in java.io.tmp directory? Could you show what you have in `System.getProperty("java.io.tmpdir")`?
Also please give us details about maven/os (`mvn --version`)

**Comment by simonjenga** [comment]
@krzyk There are intermittent results (```FAILURE/SUCCESS```) within Unit tests that have something to do with creating files in the ```temp``` Dir in my computer.

```
System.out.println(System.getProperty("java.io.tmpdir"));
C:\Users\fatcat\AppData\Local\Temp\
```

Try to reproduce this issue in the following environment:

```
Java version: 1.7.0_80, vendor: Oracle Corporation
Java home: C:\Program Files (x86)\Java\jdk1.7.0_80\jre
Apache Maven >= 3.1.1
Default locale: en_GB, platform encoding: UTF-8
OS name: "windows 7", version: "6.1", arch: "x86", family: "windows"
```

The same error messages may appear on: 
```Apache Maven 3.2.1```, ```Apache Maven 3.2.5``` and ```Apache Maven 3.3.3```

I also experience a similar problem at: https://github.com/yegor256/takes/issues/506

**Comment by simonjenga** [comment]
@krzyk 
```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.qulice.codenarc.CodeNarcValidatorTest
CodeNarc completed: (p1=0; p2=1; p3=0) 8123ms
[INFO ] com.qulice.codenarc.CodeNarcValidator: CodeNarc validated 1 file(s)
[ERROR] com.qulice.codenarc.CodeNarcValidator: C:\Users\fatcat\AppData\Local\Temp\mock7311658586797785530.qulice\basedir\src\Main.groovy[1]: Violation in class None. System.out.println s
CodeNarc completed: (p1=0; p2=0; p3=0) 6454ms
[INFO ] com.qulice.codenarc.CodeNarcValidator: CodeNarc validated 0 file(s)
CodeNarc completed: (p1=0; p2=0; p3=0) 8107ms
[INFO ] com.qulice.codenarc.CodeNarcValidator: CodeNarc validated 1 file(s)
CodeNarc completed: (p1=0; p2=1; p3=0) 8123ms
[INFO ] com.qulice.codenarc.CodeNarcValidator: CodeNarc validated 1 file(s)
[ERROR] com.qulice.codenarc.CodeNarcValidator: C:\Users\fatcat\AppData\Local\Temp\mock4784131833114347825.qulice\basedir\src\main/Foo.groovy[1]: Violation in class None. System.out.print
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 8.685 sec <<< FAILURE! - in com.qulice.codenarc.CodeNarcValidatorTest
passesExcludeFiles(com.qulice.codenarc.CodeNarcValidatorTest)  Time elapsed: 0.155 sec  <<< ERROR!
java.lang.IllegalStateException: mkdir failed
        at com.qulice.spi.Environment$Mock.<init>(Environment.java:165)
        at com.qulice.codenarc.CodeNarcValidatorTest.passesExcludeFiles(CodeNarcValidatorTest.java:89)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  CodeNarcValidatorTest.passesExcludeFiles:89 ┬╗ IllegalState mkdir failed

Tests run: 5, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................ SUCCESS [7.506s]
[INFO] qulice-spi ........................................ SUCCESS [9.169s]
[INFO] qulice-checkstyle ................................. SUCCESS [23.375s]
[INFO] qulice-pmd ........................................ SUCCESS [9.413s]
[INFO] qulice-codenarc ................................... FAILURE [10.765s]
[INFO] qulice-findbugs ................................... SKIPPED
[INFO] qulice-xml ........................................ SKIPPED
[INFO] qulice-ant ........................................ SKIPPED
[INFO] qulice-maven-plugin ............................... SKIPPED
[INFO] qulice-gradle-plugin .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running com.qulice.maven.DefaultValidatorsProviderTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec - in com.qulice.maven.DefaultValidatorsProviderTest
Running com.qulice.maven.DefaultMavenEnvironmentTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.154 sec - in com.qulice.maven.DefaultMavenEnvironmentTest
Running com.qulice.maven.CheckMojoTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.357 sec - in com.qulice.maven.CheckMojoTest
Running com.qulice.maven.DependenciesValidatorTest
Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.513 sec <<< FAILURE! - in com.qulice.maven.DependenciesValidatorT
excludesUsedUndeclaredDependencies(com.qulice.maven.DependenciesValidatorTest)  Time elapsed: 1.373 sec  <<< ERROR!
java.lang.IllegalStateException: mkdir failed
        at com.qulice.spi.Environment$Mock.<init>(Environment.java:165)
        at com.qulice.maven.MavenEnvironmentMocker.<init>(MavenEnvironmentMocker.java:81)
        at com.qulice.maven.DependenciesValidatorTest.excludesUsedUndeclaredDependencies(DependenciesValidatorTest.java:150)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Running com.qulice.maven.SvnPropertiesValidatorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.56 sec - in com.qulice.maven.SvnPropertiesValidatorTest
Running com.qulice.maven.PomXpathValidatorTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.872 sec - in com.qulice.maven.PomXpathValidatorTest
Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8

Results :

Tests in error:
  DependenciesValidatorTest.excludesUsedUndeclaredDependencies:150 ┬╗ IllegalState

Tests run: 15, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] qulice ............................................. SUCCESS [  1.092 s]
[INFO] qulice-spi ......................................... SUCCESS [  3.728 s]
[INFO] qulice-checkstyle .................................. SUCCESS [ 19.267 s]
[INFO] qulice-pmd ......................................... SUCCESS [  6.396 s]
[INFO] qulice-codenarc .................................... SUCCESS [ 10.452 s]
[INFO] qulice-findbugs .................................... SUCCESS [ 13.147 s]
[INFO] qulice-xml ......................................... SUCCESS [  4.789 s]
[INFO] qulice-ant ......................................... SUCCESS [  1.576 s]
[INFO] qulice-maven-plugin ................................ FAILURE [ 13.556 s]
[INFO] qulice-gradle-plugin ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by krzyk** [comment]
@simonjenga please update the issue description with your OS/Maven data, and it is enough to have only one log entry.

**Comment by simonjenga** [comment]
@krzyk I have already provided you with that.

**Comment by krzyk** [comment]
@simonjenga Yes, but in the comments, issue description is not very readable right now. Please leave there only the stack trace, os/maven version, tmp directly name, maven command. The rest move to an attachment.

**Comment by simonjenga** [comment]
@krzyk https://gist.github.com/simonjenga/3a3b7e51c4e5e53c74ae

**Comment by krzyk** [comment]
@simonjenga nice, but I want the description of the issue to be clear, right now it contains only some logs. Description, not comments below.

**Comment by simonjenga** [comment]
@krzyk See updated comment. 
The reason it happens is because this project generates and fills my ```temp``` Dir with a lot of folders ```>500``` and it does not delete them. I have to manually delete them to make the Build to pass.

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk I tagged this as "bug"

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk got it, someone else will be assigned soon

**Comment by davvd** [comment]
@simonjenga thank you for reporting this, I added 15 mins to your acc, transaction `78702197`

**Comment by simonjenga** [comment]
@davvd OK, thanks!

**Comment by davvd** [comment]
> @davvd OK, thanks!

@simonjenga np :)

**Comment by yegor256** [comment]
Fixed in 7a7e020be.

**Root cause:** `Environment.Mock` used `File.createTempFile()` + `delete()` + `mkdirs()` to create its basedir. This sequence is non-atomic, provided unhelpful `"init failed"` / `"mkdir failed"` errors on failure, and several downstream `mkdirs()` calls silently ignored their return values (three of them were wrapped in a no-op `if (mkdirs()) { assert file != null; }` block). When the system temp directory accumulated many leftover `mock*.qulice` dirs — I observed 29,000+ in `$TMPDIR` locally — `mkdirs` became more likely to fail and the error gave no indication of the path or the reason.

**Fix:**
- Replaced the non-atomic `createTempFile` + `delete` + `mkdirs` with `Files.createTempDirectory("mock-qulice")`, which atomically creates a uniquely-named directory.
- Every `mkdirs()` call now fails fast with a message that includes the path. For directories that can legitimately already exist (`tempdir()`, `outdir()`, classpath `target/classes`), the check is `!mkdirs() && !isDirectory()` so "already exists" is distinguished from "creation failed".
- Added regression test `EnvironmentTest#createsManyMocksWithoutFailure` that creates 200 mocks in a loop and asserts all basedirs are distinct and exist.
