### ISSUE TITLE
Issue with executions section in plugin

### ISSUE THREAD

**Issue by alex-semenyuk** [teamed/qulice#794]
When I try to exclude some class from findbugs checking like this:

```
           <plugin>
                <groupId>com.qulice</groupId>
                <artifactId>qulice-maven-plugin</artifactId>
                <version>0.17</version>
                <configuration>
                    <license>file:${basedir}/LICENSE.txt</license>
                    <excludes>
                        <exclude>findbugs:com.test.Test</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

I have the following exception:

```
Caused by: java.lang.NullPointerException
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromChildren(CollectionConverter.java:157)
	at org.codehaus.plexus.component.configurator.converters.composite.CollectionConverter.fromConfiguration(CollectionConverter.java:112)
	at org.codehaus.plexus.component.configurator.converters.ComponentValueSetter.configure(ComponentValueSetter.java:289)
	at org.codehaus.plexus.component.configurator.converters.composite.ObjectWithFieldsConverter.processConfiguration(ObjectWithFieldsConverter.java:161)
	at org.codehaus.plexus.component.configurator.BasicComponentConfigurator.configureComponent(BasicComponentConfigurator.java:56)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.populatePluginFields(DefaultMavenPluginManager.java:567)
	at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo(DefaultMavenPluginManager.java:529)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:92)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)

```
When I remove this section than everything is ok.
```
           <executions>
                    <execution>
                        <goals>
                            <goal>check</goal>
                        </goals>
                    </execution>
           </executions>
```

**Comment by krzyk** [comment]
@alex-semenyuk Is this really realted to qulice? I don't see any qulice class in the stack trace

**Comment by alex-semenyuk** [comment]
@krzyk suppose it's a maven problem which mentioned here https://github.com/teamed/qulice/issues/514 . I used maven with the version < 3.1.0. After upgrading version to the latest it works in all configuration which was mentioned above. Suppose it can be closed, but can you specify Maven's version requirements http://www.qulice.com/qulice-maven-plugin/usage.html and here https://github.com/teamed/qulice not only in contribution part?

**Comment by krzyk** [comment]
@alex-semenyuk OK, please either change the title/description of this issue or create a new one for the mvn version

**Comment by alex-semenyuk** [comment]
@krzyk Done. Does it look OK now?

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tagged this issue with "bug"

**Comment by krzyk** [comment]
@davvd this is postponed

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk sure, thanks, I added "postponed" label to it

**Comment by davvd** [comment]
> @davvd this is postponed

@krzyk I will ask somebody else to pick this up

**Comment by krzyk** [comment]
@0crat assign me

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/teamed/qulice/issues/794#issuecomment-404783015))

@krzyk The job [#794](https://github.com/teamed/qulice/issues/794) assigned to @krzyk[/z](https://www.0crat.com/u/krzyk), here is [why](https://www.0crat.com/footprint/C3T49A35L/1940959116); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @alex-semenyuk[/z](https://www.0crat.com/u/alex-semenyuk)

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
@krzyk[/z](https://www.0crat.com/u/krzyk) this job was assigned to you 5days ago. It will be taken away from you soon, unless you close it, see [§8](http://www.zerocracy.com/policy.html#8). Read [this](http://www.yegor256.com/2014/04/13/no-obligations-principle.html) and [this](http://www.yegor256.com/2014/11/24/principles-of-bug-tracking.html), please.

**Comment by krzyk** [comment]
@0crat waiting (busy with other tasks)

**Comment by 0crat** [comment]
> @0crat waiting (busy with other tasks) ([here](https://github.com/teamed/qulice/issues/794#issuecomment-407006435))

@krzyk The impediment for [#794](https://github.com/teamed/qulice/issues/794) was registered successfully by @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by krzyk** [comment]
@alex-semenyuk min maven version has been added to README and to the usage pages in #912, please close this issue

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#794](https://github.com/teamed/qulice/issues/794) is now out of scope
