### ISSUE TITLE
The build is broken in master

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#821]
```
mvn clean install -Pqulice
```
```
[INFO] [INFO] --- qulice-maven-plugin:1.0-SNAPSHOT:check (default) @ checkstyle-violations ---
[INFO] log4j:WARN No appenders could be found for logger (com.puppycrawl.tools.checkstyle.ConfigurationLoader).
[INFO] log4j:WARN Please initialize the log4j system properly.
[INFO] log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
[INFO] [INFO] Checkstyle: src/main/resources/tabs.txt[1]: Line contains a tab character. (FileTabCharacterCheck)
[INFO] [INFO] Checkstyle: src/main/resources/newlines.txt[3]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[0]: Cant find method comment (MultilineJavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[0]: Missing package-info.java file. (JavadocPackageCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[0]: Problem finding class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[1]: Line does not match expected header line of '/**'. (HeaderCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[5]: Missing a Javadoc comment. (JavadocTypeCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[6]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[6]: Method 'test' is not designed for extension - needs to be abstract, final or empty. (DesignForExtensionCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[6]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[13]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[14]: Parameter txt should be final. (FinalParametersCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[22]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[25]: Parameter ex should be final. (FinalParametersCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[32]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[33]: ArrayList should be initialized with a size parameter (ConditionalRegexpMultilineCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Violations.java[34]: ArrayList should be initialized with a size parameter (RegexpMultilineCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/IndentationChecks.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/IndentationChecks.java[6]: Missing '@author' tag in class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/IndentationChecks.java[6]: Missing '@since' tag in class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/IndentationChecks.java[6]: Missing '@version' tag in class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/IndentationChecks.java[14]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Constants.java[32]: Missing '@since' tag in class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Constants.java[39]: Missing a Javadoc comment. (JavadocVariableCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Constants.java[41]: Missing a Javadoc comment. (JavadocVariableCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Constants.java[43]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Constants.java[43]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Constants.java[47]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Constants.java[47]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[0]: Cant find method comment (MultilineJavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[0]: Problem finding class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[2]: Missing a Javadoc comment. (JavadocTypeCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[3]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[3]: Method 'test' is not designed for extension - needs to be abstract, final or empty. (DesignForExtensionCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[3]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[4]: Line contains a tab character. (FileTabCharacterCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Tabs.java[5]: Indentation (4) must be same or less than previous line (1), or bigger by exactly 4 (CascadeIndentationCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[0]: Cant find method comment (MultilineJavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[0]: Problem finding class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[3]: Missing a Javadoc comment. (JavadocTypeCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[3]: The name of the outer type and the file do not match. (OuterTypeFilenameCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[4]: Private constant "name" is not used (ConstantUsageCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[4]: Missing a Javadoc comment. (JavadocVariableCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[5]: Missing a Javadoc comment. (JavadocVariableCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[6]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Iface.java[6]: Redundant 'public' modifier. (RedundantModifierCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[0]: Problem finding class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[3]: Missing a Javadoc comment. (JavadocTypeCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[9]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[9]: Method 'test' is not designed for extension - needs to be abstract, final or empty. (DesignForExtensionCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[17]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[23]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[23]: Method 'inner' is not designed for extension - needs to be abstract, final or empty. (DesignForExtensionCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[24]: Comments in method body are prohibited (MethodBodyCommentsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Pdd.java[25]: Comments in method body are prohibited (MethodBodyCommentsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/SomeTest.java[0]: Cant find method comment (MultilineJavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/SomeTest.java[0]: Problem finding class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/SomeTest.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/SomeTest.java[3]: Missing a Javadoc comment. (JavadocTypeCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/SomeTest.java[5]: Method 'testing' is not designed for extension - needs to be abstract, final or empty. (DesignForExtensionCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/SomeTest.java[5]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/NewLines.java[0]: Cant find method comment (MultilineJavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/NewLines.java[0]: Problem finding class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/NewLines.java[1]: Missing a Javadoc comment. (JavadocTypeCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/NewLines.java[1]: Missing a header - not enough lines in file. (HeaderCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/NewLines.java[1]: Missing package declaration. (PackageDeclarationCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/NewLines.java[2]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/NewLines.java[2]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/NewLines.java[4]: Lines in file should end with Unix-like end of line (RegexpMultilineCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Brackets.java[34]: Missing '@since' tag in class/interface comment (JavadocTagsCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Brackets.java[47]: Parameters should start on a new line (BracketsStructureCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Brackets.java[50]: Parameters should start on a new line (BracketsStructureCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Brackets.java[53]: Parameters should start on a new line (BracketsStructureCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Brackets.java[57]: Closing bracket should be on a new line (BracketsStructureCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Brackets.java[60]: This method must be static, because it does not refer to "this" (NonStaticMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Brackets.java[60]: Missing a Javadoc comment. (JavadocMethodCheck)
[INFO] [INFO] Checkstyle: src/main/java/com/qulice/plugin/violations/Brackets.java[77]: Redundant 'public' modifier. (RedundantModifierCheck)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[34-34]: Unnecessary use of fully qualified name 'java.util.ArrayList' due to existing import 'java.util.ArrayList' (UnnecessaryFullyQualifiedName)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[36-36]: Unnecessary use of fully qualified name 'java.util.ArrayList' due to existing import 'java.util.ArrayList' (UnnecessaryFullyQualifiedName)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[15-15]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[33-33]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[34-34]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[35-35]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[36-36]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[14-14]: Local variable 'txt' could be declared final (LocalVariableCouldBeFinal)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Violations.java[7-7]: The String literal "test" appears 2 times in this file; the first occurrence is on line 7 (AvoidDuplicateLiterals)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/IndentationChecks.java[15-15]: Avoid instantiating String objects; this is usually unnecessary. (StringInstantiation)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Constants.java[44-44]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Constants.java[48-48]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Constants.java[39-39]: The String literal "test" appears 2 times in this file; the first occurrence is on line 39 (AvoidDuplicateLiterals)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Iface.java[4-4]: This final field could be made static (FinalFieldCouldBeStatic)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Iface.java[3-9]: Avoid doing field initialization outside constructor. (ConstructorShouldDoInitialization)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Iface.java[5-5]: Perhaps 'iaccount' could be replaced by a local variable. (SingularField)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Iface.java[4-4]: Avoid unused private fields such as 'name'. (UnusedPrivateField)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Iface.java[5-5]: Avoid unused private fields such as 'iaccount'. (UnusedPrivateField)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Pdd.java[18-18]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Pdd.java[26-26]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/SomeTest.java[6-6]: System.out.println is used (SystemPrintln)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/NewLines.java[2-3]: Document empty method body (UncommentedEmptyMethodBody)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/NewLines.java[1-4]: All classes and interfaces must belong to a named package (NoPackage)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Brackets.java[56-56]: Avoid unused local variables such as 'atom'. (UnusedLocalVariable)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Brackets.java[60-60]: Avoid unused method parameters such as 'start'. (UnusedFormalParameter)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Brackets.java[60-60]: Avoid unused method parameters such as 'end'. (UnusedFormalParameter)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Brackets.java[77-77]: Avoid unused constructor parameters such as 'start'. (UnusedFormalParameter)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Brackets.java[77-77]: Avoid unused constructor parameters such as 'list'. (UnusedFormalParameter)
[INFO] [INFO] PMD: src/main/java/com/qulice/plugin/violations/Brackets.java[77-77]: Avoid unused constructor parameters such as 'rest'. (UnusedFormalParameter)
[INFO] [INFO] Read our quality policy: http://www.qulice.com/quality.html
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] BUILD FAILURE
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [INFO] Total time: 4.360 s
[INFO] [INFO] Finished at: 2017-02-03T11:29:12+02:00
[INFO] [INFO] Final Memory: 31M/682M
[INFO] [INFO] ------------------------------------------------------------------------
[INFO] [WARNING] The requested profile "qulice" could not be activated because it does not exist.
[INFO] [ERROR] Failed to execute goal com.qulice:qulice-maven-plugin:1.0-SNAPSHOT:check (default) on project checkstyle-violations: Failure: There are 109 violations -> [Help 1]
[INFO] org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qulice:qulice-maven-plugin:1.0-SNAPSHOT:check (default) on project checkstyle-violations: Failure
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
[INFO] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
[INFO] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[INFO] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
[INFO] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
[INFO] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
[INFO] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
[INFO] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[INFO] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[INFO] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[INFO] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[INFO] 	at java.lang.reflect.Method.invoke(Method.java:498)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
[INFO] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
[INFO] Caused by: org.apache.maven.plugin.MojoFailureException: Failure
[INFO] 	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:72)
[INFO] 	at com.qulice.maven.AbstractQuliceMojo.execute(AbstractQuliceMojo.java:172)
[INFO] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
[INFO] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
[INFO] 	... 20 more
[INFO] Caused by: com.qulice.spi.ValidationException: There are 109 violations
[INFO] 	at com.qulice.maven.CheckMojo.run(CheckMojo.java:116)
[INFO] 	at com.qulice.maven.CheckMojo.doExecute(CheckMojo.java:66)
[INFO] 	... 23 more
[INFO] [ERROR] 
[INFO] [ERROR] Re-run Maven using the -X switch to enable full debug logging.
[INFO] [ERROR] 
[INFO] [ERROR] For more information about the errors and possible solutions, please read the following articles:
[INFO] [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[INFO] run script verify.groovy
[INFO] Running post-build script: /home/papolishchuk/pr/qulice/qulice-maven-plugin/target/it/checkstyle-violations/verify.groovy
[INFO] ..FAILED (5.4 s)
```

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by krzyk** [comment]
@longtimeago I wonder how that happened :)

**Comment by krzyk** [comment]
@davvd valid bug

**Comment by davvd** [comment]
> @davvd valid bug

@krzyk tag bug added to this issue

**Comment by yegor256** [comment]
@krzyk I didn't do anything, I swear! Or did I?.. :)

**Comment by krzyk** [comment]
@0crat in

**Comment by krzyk** [comment]
@longtimeago I think I fixed in in #879, could you check?

**Comment by krzyk** [comment]
@longtimeago ping

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @krzyk[/z](https://www.0crat.com/u/krzyk)

**Comment by 0crat** [comment]
The job [#821](https://github.com/teamed/qulice/issues/821) is now out of scope
