### ISSUE TITLE
DefaultValidatorsProvider.java:84-86: Make XmlValidator and...

### ISSUE THREAD

**Issue by 0pdd** [teamed/qulice#849]
The puzzle `61-1e86e587` (from #61) in [`qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultValidatorsProvider.java`](https://github.com/teamed/qulice/blob/master/qulice-maven-plugin/src/main/java/com/qulice/maven/DefaultValidatorsProvider.java) (lines 84-86) has to be resolved: "Make XmlValidator and CodeNarcValidator inherit from ResourceValidator and use it similarly to CheckstyleValidator. Remember to move it to externalResource method and make sure all the tests pass."

The puzzle was created by krzyk on 27-Feb-16. 

Estimate: 30 minutes, role: IMP.

If you have any technical questions, don't ask me, submit new tickets instead. The task will be "done" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by 0pdd** [comment]
The puzzle `61-1e86e587` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by 0crat** [comment]
There is an unrecoverable failure on my side. Please, submit it [here](https://github.com/zerocracy/datum):

```
java.io.IOException: java.lang.IllegalStateException: Failed to acquire "2017/01/C3T49A35L/claims.xml" in 20s
	at org.cactoos.func.IoCheckedFunc.apply(IoCheckedFunc.java:74)
	at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:60)
	at com.zerocracy.farm.UplinkedProject.acq(UplinkedProject.java:100)
	at com.zerocracy.farm.reactive.RvProject.acq(RvProject.java:61)
	at com.zerocracy.farm.ruled.RdProject.acq(RdProject.java:54)
	at com.zerocracy.radars.github.GhProject.acq(GhProject.java:78)
	at com.zerocracy.pm.Claims.lock(Claims.java:65)
	at com.zerocracy.pm.ClaimOut.postTo(ClaimOut.java:75)
	at com.zerocracy.radars.github.RbOnClose.react(RbOnClose.java:57)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbByActions.react(RbByActions.java:65)
	at com.zerocracy.radars.github.Rebound$Chain.react(Rebound.java:74)
	at com.zerocracy.radars.github.RbSafe.lambda$react$0(RbSafe.java:66)
	at org.cactoos.func.FuncWithFallback.appl...
```

**Comment by yegor256** [comment]
hey

**Comment by yegor256** [comment]
@0crat hey

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 502fe8f 2017-09-30T08:19:36
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.IllegalStateException: Can't post anything to teamed/qulice#849, too many comments already
	at sun.reflect.GeneratedConstructorAccessor309.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
	at com.zerocracy.stk.pm.comm.notify_in_github.safe(notify_in_github.groovy:89)
	at com.zerocracy.stk.pm.comm.notify_in_github$safe.callStatic(Unknown Source)
	at com.zerocracy.stk.pm.comm.notify_in_github.exec(notify_in_github.groovy:62)
	at sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source)
	at sun.reflect.Delegat...
```

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT 502fe8f 2017-09-30T08:19:36
IllegalStateException: java.lang.reflect.InvocationTargetException
java.lang.IllegalStateException: Can't post anything to teamed/qulice#849, too many comments already
	at sun.reflect.GeneratedConstructorAccessor309.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:77)
	at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrapNoCoerce.callConstructor(ConstructorSite.java:102)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:190)
	at com.zerocracy.stk.pm.comm.notify_in_github.safe(notify_in_github.groovy:89)
	at com.zerocracy.stk.pm.comm.notify_in_github$safe.callStatic(Unknown Source)
	at com.zerocracy.stk.pm.comm.notify_in_github.exec(notify_in_github.groovy:62)
	at sun.reflect.GeneratedMethodAccessor225.invoke(Unknown Source)
	at sun.reflect.Delegat...
```

**Comment by 0crat** [comment]
> @0crat hey ([here](https://github.com/teamed/qulice/issues/849#issuecomment-333315832))

@yegor256 Hey, what's up, how is it going?
