### ISSUE TITLE
Failed ChecksTest#testCheckstyleTruePositive doesn't fail the build

### ISSUE THREAD

**Issue by longtimeago** [teamed/qulice#858]
See http://www.rultor.com/t/13190-338250233
```java
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running [15]
Tests run: 32, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 1.031 sec <<< FAILURE! - in [15]
testCheckstyleTruePositive[10](com.qulice.checkstyle.ChecksTest)  Time elapsed: 0.816 sec  <<< FAILURE!
java.lang.AssertionError:

Expected: Line no.10 ('Reference to instance variable 'number' needs "this.".') not reported by ChecksTest/RequireThisCheck: ''
     but: was <false>
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:8)
        at com.qulice.checkstyle.ChecksTest.testCheckstyleTruePositive(ChecksTest.java:136)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
        at java.lang.Thread.run(Thread.java:748)
```
But the (merging) build still succeed :(
Release build fails (https://github.com/teamed/qulice/issues/798)

**Comment by 0crat** [comment]
@krzyk please, pay attention to this issue

**Comment by longtimeago** [comment]
nah, I was wrong

**Comment by 0crat** [comment]
Oops! There is no order for job `gh:teamed/qulice#858`.

**Comment by 0crat** [comment]
Oops! Job `gh:teamed/qulice#858` is not in scope.
