### ISSUE TITLE
FindBugsValidatorTest.throwsExceptionOnViolation test is broken

### ISSUE THREAD

**Issue by korthout** [teamed/qulice#989]
Running `mvn test` on `master` branch (on macOS 10.14.2) fails resulting in:

```
Tests run: 6, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 27.27 sec <<< FAILURE! - in com.qulice.findbugs.FindBugsValidatorTest
throwsExceptionOnViolation(com.qulice.findbugs.FindBugsValidatorTest)  Time elapsed: 25.773 sec  <<< FAILURE!
java.lang.AssertionError: Expected exception: com.qulice.spi.ValidationException
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:32)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:387)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

This should be fixed and should not disturb development of other things.

**Comment by zCRUSADERz** [comment]
I also ran into this problem. As a result of the research, I found the cause of this error. In my case,  `FindBugs` uses the asm 5.0.3 library, class: `ClassReader`, which works with bytecode version 1.8, not higher. The command line call: `java -version` = 1.8, and `javac -version` = 11.0.2, which led to the error.

**Comment by zCRUSADERz** [comment]
@korthout Please check your version of Java and try running tests again on version 1.8.

**Comment by korthout** [comment]
@zCRUSADERz Interesting. This did seem to solve it when running `mvn test`, but the test still fails within IntelliJ. Perhaps somehow my IntelliJ version uses a Java version > 8. I'll close the issue and corresponding PR, because this at least solves the original issue.

**Comment by 0crat** [comment]
Job `gh:teamed/qulice#989` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
